version: '3'

services:
  master1:
    container_name: master1-replicas
    image: redis:6.2.7
    ports:
      - "6479:6379"
    volumes:
      - ./master1/conf:/conf
      - ./master1/data:/data
    restart: always
    networks:
      redis:
        ipv4_address: 172.16.239.3
    command: [
      'redis-server',
      '/conf/redis.conf'
    ]
  slave1:
    container_name: slave1-replicas
    image: redis:6.2.7
    ports:
      - "6480:6379"
    volumes:
      - ./slave1/conf:/conf
      - ./slave1/data:/data
    restart: always      
    networks:
      redis:
        ipv4_address: 172.16.239.7
    command: [
      'redis-server',
      '/conf/redis.conf'
    ]
  sentinel1:
    container_name: sentinel1
    image: redis:6.2.7
    ports:
      - "6481:26379"
    volumes:
      - ./sentinel1/conf:/conf
      - ./sentinel1/data:/data    
    networks:
      redis:
        ipv4_address: 172.16.239.8
    depends_on:
      - master1
      - slave1
  sentinel2:
    container_name: sentinel2
    image: redis:6.2.7
    ports:
      - "6482:26379"
    volumes:
      - ./sentinel2/conf:/conf
      - ./sentinel2/data:/data
    restart: always      
    networks:
      redis:
        ipv4_address: 172.16.239.9
    depends_on:
      - master1
      - slave1
  sentinel3:
    container_name: sentinel3
    image: redis:6.2.7
    ports:
      - "6483:26379"
    volumes:
      - ./sentinel3/conf:/conf
      - ./sentinel3/data:/data
    restart: always      
    networks:
      redis:
        ipv4_address: 172.16.239.10
    depends_on:
      - master1
      - slave1
networks:
  redis:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
volumes:
  datamaster1-replicas:
  dataslave1-replicas:
  
# redis-sentinel /conf/sentinel.conf
# redis-cli --cluster create --cluster-replicas 1 172.16.237.3:6379 172.16.237.4:6379 172.16.237.5:6379 172.16.237.6:6379 172.16.237.7:6379 172.16.237.8:6379