version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.23.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log:/var/log/nginx/
    ports:
      - "80:80"
      - "81:81"
    networks:
      - redis-cluster_redis

networks:
  redis-cluster_redis:
    external: true
